/**
 * Past Papers corpus — SERVER-ONLY access to the syllabai-pastpapers index.
 *
 * The corpus repo is ~4 GB of canonical PDFs we NEVER clone or vendor. The
 * committed index (src/data/pastpapers-index.json, generated by
 * scripts/build_pastpapers_index.ts from the git tree) holds the inventory:
 * which paper dirs exist per specification, and which materials (qp.pdf /
 * ms.pdf / er.pdf) each holds. PDFs themselves stream at runtime from
 * raw.githubusercontent.com (CORS-enabled) so the demo hosts nothing.
 *
 * This module imports the index JSON — import it ONLY from server
 * components; client components use @/lib/pastpapers-shared instead.
 *
 * Honesty rules (non-negotiable, demo discipline):
 *   - Corpus metadata is AI-IDENTIFIED (operator ratification pending) — the
 *     index is derived from the canonical layout, full manifests live in the
 *     corpus repo. Every surface says so.
 *   - Official exam durations are shown ONLY where attested in
 *     OFFICIAL_DURATIONS; anything else is an editable estimate labelled as
 *     such in the mock runner.
 *   - Interactive (Mode 2) papers exist ONLY where the parsed question corpus
 *     attests them (sourcePaper provenance, lib/past-papers.ts); everything
 *     else gets the honest "parsing roadmap" state, never a fake player.
 */
import indexJson from "@/data/pastpapers-index.json";
import {
  corpusRawPath,
  ialUnitTitle,
  sessionRankOf,
  specTitle,
  type CorpusIndexMeta,
  type CorpusPaper,
  type CorpusPaperEntry,
  type CorpusSession,
  type CorpusSpec,
} from "@/lib/pastpapers-shared";

// ── index (server-side) ────────────────────────────────────────────────────
interface CorpusIndex {
  meta: CorpusIndexMeta;
  specs: Record<string, CorpusSpec>;
}

export const corpusIndex = indexJson as unknown as CorpusIndex;
export {
  corpusRawUrl,
  corpusRawPath,
  sessionLabel,
  groupBySession,
  prettyBytes,
  specTitle,
} from "@/lib/pastpapers-shared";
export type { CorpusPaperEntry } from "@/lib/pastpapers-shared";

// ── course → corpus mapping ────────────────────────────────────────────────
/** Which corpus specs a demo course draws from, plus optional filters. */
interface CourseSpecMap {
  specs: string[];
  /** IAL maths 2018 lives in ONE spec folder — filter by unit code prefix. */
  units?: string[];
  /** 4MA1 tier filter: "F" (foundation) or "H" (higher). */
  tier?: "F" | "H";
}

const IG = "pearson-edexcel/international-gcse";
const IA = "pearson-edexcel/international-a-level";

const COURSE_SPECS: Record<string, CourseSpecMap> = {
  "igcse-chemistry-19": { specs: [`${IG}/chemistry/4ch1`] },
  "igcse-physics-19": { specs: [`${IG}/physics/4ph1`] },
  "igcse-biology-19": { specs: [`${IG}/biology/4bi1`] },
  "igcse-maths-a-18-foundation": { specs: [`${IG}/mathematics-a/4ma1`], tier: "F" },
  "igcse-maths-a-18-higher": { specs: [`${IG}/mathematics-a/4ma1`], tier: "H" },
  "igcse-maths-b-16": { specs: [`${IG}/mathematics-b/4mb1`] },
  "igcse-further-maths-19": { specs: [`${IG}/further-pure-mathematics/4pm1`] },
  "igcse-accounting-17-financial-statements": { specs: [`${IG}/accounting/4ac1`] },
  "igcse-accounting-17-introduction-to-bookkeeping-and-accounting": {
    specs: [`${IG}/accounting/4ac1`],
  },
  "igcse-business-19": { specs: [`${IG}/business/4bs1`] },
  "igcse-economics-17": { specs: [`${IG}/economics/4ec1`] },
  "igcse-ict-17": { specs: [`${IG}/ict/4it1`] },
  "igcse-english-language-a-16-paper-1-non-fiction-texts-and-transactional-writing": {
    specs: [`${IG}/english-language-a/4ea1`],
  },
  "igcse-english-language-a-16-paper-2-poetry-and-prose-texts-and-imaginative-writing": {
    specs: [`${IG}/english-language-a/4ea1`],
  },
  "igcse-english-language-a-16-paper-3-coursework": { specs: [`${IG}/english-language-a/4ea1`] },
  "igcse-english-literature-16": { specs: [`${IG}/english-literature/4et1`] },
  "igcse-geography-19": { specs: [`${IG}/geography/4ge1`] },
  "ial-chemistry-17": {
    specs: [`${IA}/chemistry/wch11`, `${IA}/chemistry/wch12`, `${IA}/chemistry/wch13`, `${IA}/chemistry/wch14`, `${IA}/chemistry/wch15`, `${IA}/chemistry/wch16`],
  },
  "ial-physics-19": {
    specs: [`${IA}/physics/wph11`, `${IA}/physics/wph12`, `${IA}/physics/wph13`, `${IA}/physics/wph14`, `${IA}/physics/wph15`, `${IA}/physics/wph16`],
  },
  "ial-biology-18": {
    specs: [`${IA}/biology/wbi11`, `${IA}/biology/wbi12`, `${IA}/biology/wbi13`, `${IA}/biology/wbi14`, `${IA}/biology/wbi15`, `${IA}/biology/wbi16`],
  },
  "ial-maths-20-pure-1": { specs: [`${IA}/mathematics/mathematics-2018`], units: ["WMA11"] },
  "ial-maths-20-pure-2": { specs: [`${IA}/mathematics/mathematics-2018`], units: ["WMA12"] },
  "ial-maths-20-pure-3": { specs: [`${IA}/mathematics/mathematics-2018`], units: ["WMA13"] },
  "ial-maths-20-pure-4": { specs: [`${IA}/mathematics/mathematics-2018`], units: ["WMA14"] },
  "ial-maths-20-mechanics-1": { specs: [`${IA}/mathematics/mathematics-2018`], units: ["WME01"] },
  "ial-maths-20-mechanics-2": { specs: [`${IA}/mathematics/mathematics-2018`], units: ["WME02"] },
  "ial-maths-20-statistics-1": { specs: [`${IA}/mathematics/mathematics-2018`], units: ["WST01"] },
  "ial-maths-20-statistics-2": { specs: [`${IA}/mathematics/mathematics-2018`], units: ["WST02"] },
  "ial-maths-20-decision-1": { specs: [`${IA}/mathematics/mathematics-2018`], units: ["WDM11"] },
  "ial-further-maths-18-further-pure-1": {
    specs: [`${IA}/mathematics/mathematics-2018`],
    units: ["WFM01"],
  },
};

export function corpusSpecsForCourse(slug: string): CourseSpecMap | null {
  return COURSE_SPECS[slug] ?? null;
}

// ── official exam durations (attested) ─────────────────────────────────────
/**
 * Official exam durations (minutes) — ATTESTED Edexcel timings only.
 * Keyed by full IGCSE reference ("4CH1/1C") or IAL unit code ("WCH11").
 * Everything not listed = null → the mock runner shows an editable estimate.
 */
const OFFICIAL_DURATIONS: Record<string, number> = {
  // IGCSE Sciences (2017 linear): Paper 1 = 2h, Paper 2 = 1h10 (Chem) / 1h15 (Phy/Bio)
  "4CH1/1C": 120, "4CH1/1CR": 120, "4CH1/2C": 70, "4CH1/2CR": 70,
  "4PH1/1P": 120, "4PH1/1PR": 120, "4PH1/2P": 75, "4PH1/2PR": 75,
  "4BI1/1B": 120, "4BI1/1BR": 120, "4BI1/2B": 75, "4BI1/2BR": 75,
  // IGCSE Maths A: Higher 1H/2H = 2h, Foundation 1F/2F = 1h30
  "4MA1/1H": 120, "4MA1/2H": 120, "4MA1/1F": 90, "4MA1/2F": 90,
  "4MA1/1HR": 120, "4MA1/2HR": 120, "4MA1/1FR": 90, "4MA1/2FR": 90,
  // IGCSE Further Pure Maths: Papers 1 & 2 = 2h
  "4PM1/1": 120, "4PM1/2": 120,
  "4MB1/1": 120, "4MB1/2": 120,
  // IAL 2018 sciences: units 1/2 = 1h30, unit 3 = 1h20, units 4/5 = 1h45 (Phy 1h35), unit 6 = 1h50
  WCH11: 90, WCH12: 90, WCH13: 80, WCH14: 105, WCH15: 105, WCH16: 110,
  WPH11: 90, WPH12: 90, WPH13: 80, WPH14: 95, WPH15: 95, WPH16: 110,
  WBI11: 90, WBI12: 90, WBI13: 80, WBI14: 105, WBI15: 105, WBI16: 110,
  // IAL 2018 maths modules: 1h30 each
  WMA11: 90, WMA12: 90, WMA13: 90, WMA14: 90,
  WME01: 90, WME02: 90, WME03: 90,
  WST01: 90, WST02: 90, WST03: 90,
  WDM11: 90,
  WFM01: 90, WFM02: 90, WFM03: 90,
};

function officialDuration(ref: string): number | null {
  if (OFFICIAL_DURATIONS[ref] != null) return OFFICIAL_DURATIONS[ref];
  const unit = ref.split("/")[0];
  return OFFICIAL_DURATIONS[unit] ?? null;
}

// ── entry construction ─────────────────────────────────────────────────────
function buildEntry(
  specKey: string,
  spec: CorpusSpec,
  sessionId: string,
  p: CorpusPaper,
): CorpusPaperEntry | null {
  // split dir at the LAST dash: "4CH1-1C" → 4CH1 + 1C; "WMA11-01A" → WMA11 + 01A
  const cut = p.d.lastIndexOf("-");
  if (cut <= 0 || cut === p.d.length - 1) return null;
  const unit = p.d.slice(0, cut);
  const variant = p.d.slice(cut + 1);
  const ref = `${unit}/${variant}`;
  const isIGCSE = spec.qual === "international-gcse";

  let title: string;
  let variantChip: string | null = null;
  if (isIGCSE) {
    title = `Paper ${variant}`;
    // "1CR" → Timezone R (SME wording); "1C" → no chip
    const tz = variant.match(/^(\d+[A-Z])R$/);
    if (tz) {
      title = `Paper ${tz[1]}`;
      variantChip = "Timezone R";
    }
  } else {
    title = ialUnitTitle(unit);
    const v = variant.match(/^0\d([A-Z])$/);
    if (v) variantChip = `Variant ${v[1]}`;
  }

  return {
    specKey,
    specTitle: specTitle(spec),
    qual: spec.qual,
    sessionId,
    dir: p.d,
    unit,
    variant,
    ref,
    title,
    variantChip,
    qpBytes: p.qp,
    msBytes: p.ms,
    erBytes: p.er,
    durationMin: officialDuration(ref),
    qpPath: p.qp != null ? corpusRawPath(specKey, sessionId, p.d, "qp.pdf") : "",
    msPath: p.ms != null ? corpusRawPath(specKey, sessionId, p.d, "ms.pdf") : "",
  };
}

/**
 * All corpus papers for a course, flattened. Sorted newest session first,
 * then by reference. Papers missing BOTH qp and ms are dropped (nothing to
 * view).
 */
export function corpusPapersForCourse(slug: string): CorpusPaperEntry[] {
  const map = COURSE_SPECS[slug];
  if (!map) return [];
  const out: CorpusPaperEntry[] = [];
  for (const specKey of map.specs) {
    const spec = corpusIndex.specs[specKey];
    if (!spec) continue;
    for (const session of spec.sessions as CorpusSession[]) {
      for (const p of session.papers as CorpusPaper[]) {
        if (p.qp == null && p.ms == null) continue;
        const entry = buildEntry(specKey, spec, session.id, p);
        if (!entry) continue;
        if (map.units && !map.units.includes(entry.unit)) continue;
        if (map.tier) {
          // 4MA1 variants: 1F/2F (foundation), 1H/2H (higher), optional R suffix
          const isH = entry.variant.includes("H");
          const isF = entry.variant.includes("F");
          if (map.tier === "H" && !isH) continue;
          if (map.tier === "F" && !isF) continue;
        }
        out.push(entry);
      }
    }
  }
  return out.sort(
    (a, b) =>
      sessionRankOf(b.sessionId) - sessionRankOf(a.sessionId) ||
      a.ref.localeCompare(b.ref) ||
      a.dir.localeCompare(b.dir),
  );
}

/** True when the corpus holds at least one mapped paper for this course. */
export function courseHasCorpusPapers(slug: string): boolean {
  return corpusPapersForCourse(slug).length > 0;
}

export function findCorpusPaper(
  slug: string,
  sessionId: string,
  dir: string,
): CorpusPaperEntry | null {
  return corpusPapersForCourse(slug).find((p) => p.sessionId === sessionId && p.dir === dir) ?? null;
}
